RestaurantService/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RestaurantService.Data.Models;
using RestaurantService.Models;
using RestaurantService.Services.Contracts;

namespace RestaurantService.Controllers
{
    public class CommentController : Controller
    {
        private readonly IEstablishmentService establishmentService;
        private readonly IMapper<EstablishmentViewModel, Establishment> establishmentMapper;
        private readonly IClientCommentService commentService;
        private readonly IModerationService moderationService;
        private readonly UserManager<ApplicationUser> userManager;

        public CommentController(IEstablishmentService establishmentService,
            IMapper<EstablishmentViewModel, Establishment> establishmentMapper,
            IClientCommentService commentService,
            IModerationService moderationService,
            UserManager<ApplicationUser> userManager)
        {
            this.establishmentService = establishmentService;
            this.establishmentMapper = establishmentMapper;
            this.commentService = commentService;
            this.moderationService = moderationService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> SaveComment(ClientCommentViewModel model)
        {
            ClientComment comment = null;
            if (string.IsNullOrEmpty(model.Author)) model.Author = "Anonymous";
            try
            {
                if (!string.IsNullOrEmpty(model.Text))
                {
                    var totalWords = model.Text.Split(' ', ',', '.').Select(w => w.Replace(" ", "")
                                                                                  .Replace("!", "")
                                                                                  .Replace("?", "")
                                                                                  .Replace(",", "")
                                                                                  .Replace(";", "")
                                                                                  .Replace(".", ""))
                                                                                  .ToList();
                    var uniqueWords = new HashSet<string>(totalWords);
                    model.CommentWords = uniqueWords.ToList();
                    model.Date = DateTime.Now;
                    var swearWords = await this.commentService.CheckForSwearWords(model.CommentWords);
                    var swearAll = totalWords.Where(w => swearWords.Contains(w.ToLower())).Count();
                    if (swearWords.Count > 0)
                    {
                        foreach (var word in model.CommentWords)
                        {
                            if (swearWords.Contains(word.ToLower()))
                            {
                                model.Text = (model.Text).Replace(word, "***");
                            }
                        }
                    }
                    if (swearAll > totalWords.Count / 5)
                    {
                        model.Text = "";
                        model.ModerationReason = "inappropriate language";
                        model.ModerationDate = DateTime.Now;
                    }
                    else
                    {
                        if (swearWords.Count > 0)
                        {
                            var reason = await this.moderationService.GetReasonByName("inappropriate language");
                            var moderation = await this.moderationService.CreateModeration(reason.Id, null);
                            model.Moderation = moderation;
                            model.ModerationReason = "inappropriate language";
                            model.ModerationDate = DateTime.Now;
                        }
                        comment = await this.commentService.AddComment(model.EstablishmentId, model.Text, model.Author, model.Moderation);
                    }
                }
                return PartialView("_ClientCommentPartial", model);
            }
            catch (ArgumentException ex)
            {
                return PartialView("_CustomError", new CustomErrorViewModel { ExceptionMessage = ex.Message });
            }
        }



        [HttpPost]
        public async Task<IActionResult> EditComment(string text, int id, int moderation, int page)
        {
            var reason = await this.moderationService.GetReasonById(moderation);
            var moderationEntity = await this.moderationService.CreateModeration(reason?.Id, userManager.GetUserId(User));
            var comment = await this.commentService.UpdateComment(id,text,moderationEntity?.Id);
            return RedirectToAction("Details", "Establishment", new {id= comment.EstablishmentId, page=page});
        }

        public IActionResult InvalidComment(ClientCommentViewModel model)
        {
            return PartialView("_LeaveClientCommentPartial", model);
        }
    }
}

RestaurantService/Views/Comment/_ClientCommentPartial.cshtml
@inject UserManager<ApplicationUser> UserManager
@model ClientCommentViewModel

<div class="card px-3 align-left col-12">
    <div class="panel-item p-4 d-flex align-items-start">
        <div class="card-img pr-3">
            <h4 class="mbr-content-title mbr-bold mbr-fonts-style display-7" style="text-align:right">
                @Model.Date.ToString("MM.dd")

            </h4>
            <h4 class="mbr-content-title mbr-bold mbr-fonts-style display-7" style="text-align:right">
                @Model.Date.ToString("yyyy")

            </h4>
            <h4 class="  mbr-fonts-style display-7" style="text-align:right">
                [@Model.Date.ToString("HH:mm")]
            </h4>
        </div>

        <div class="card-text">

            <table style="width:250px">
                <tr>
                    <td>
                        <h3 class="img-text d-flex ">
                            @Model.Author
                        </h3>
                    </td>
                    <td style="text-align:right">
                        @if (User.IsInRole("Moderator"))
                        {
                            <span style="width:100px;font-size:1.2rem" class="moderation-edit-link">
                                <a href="#" class="btn btn-primary">
                                    Edit
                                </a>
                            </span>
                        }
                    </td>
                </tr>
            </table>
            <div class="client-comment-returned-text">
                <div class="moderation-edit-paragraph">
                    <p class="mbr-content-text mbr-fonts-style display-7">
                        @Model.Text
                    </p>
                    @if (!string.IsNullOrEmpty(Model.ModerationReason) || !string.IsNullOrEmpty(Model.ModerationAuthor))
                    {
                        <p style="color:red">
                            Moderated
                            @if (!string.IsNullOrEmpty(Model.ModerationReason))
                            {
                                <span> for @Model.ModerationReason</span>
                            }

                            @if (!string.IsNullOrEmpty(Model.ModerationAuthor))
                            {
                                <span> by  @Model.ModerationAuthor</span>
                            }
                            <span> on @Model.ModerationDate.ToString("dd.MM.yyyy")</span>
                        </p>
                    }
                </div>
                <div class="moderation-edit-form" style="background-color:#bdbdbd">
                    <form method="post" class="mbr-form form-with-styler" data-form-title="Mobirise Form">
                        @*<label asp-for="Text"></label>*@
                        <textarea rows="3" cols="60" style="width:100%;margin:0;text-align:left;opacity:1;display:block!important" name="text" class="client-comment-input" value=@Model.Text.Trim() ></textarea>
                        <input type="hidden" value="@Model.Id" name="id" />
                        <input type="hidden" name="page" value=@Model.Page>
                        <table style="width:100%">
                            <tr>
                                <td style="padding:5px;padding-top:0">
                                    @if (ViewBag.ModerationReasons != null && ViewBag.ModerationReasons.Count > 0)
                                    {
                                        <div>
                                            @foreach (var item in ViewBag.ModerationReasons)
                                            {
                                                <span style="display:block">
                                                    <input type="radio"
                                                           name="moderation"
                                                           @if (Model.ModerationReason == item.Name) { <text> checked="checked" </text> }
                                                           value=@item.Id /> @item.Name
                                                    </span>

                                                }
                                        </div>
                                    }
                                </td>
                                <td style="width:100px;padding-right:5px">
                                    <button type="submit"
                                            formmethod="post"
                                            asp-controller="Comment"
                                            asp-action="EditComment"
                                            class="btn btn-primary"
                                            style="
                                                /*border-radius:4px;
                                                border:1px solid #149dcc!important;
                                                background-color:white!important;
                                                color:#149dcc!important;
                                                float:right;
                                                margin-right:3.5vw*/">
                                        &nbsp;Ok&nbsp;&nbsp;
                                    </button>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

RestaurantService/Views/Comment/_EditCommentPartial.cshtml
@inject UserManager<ApplicationUser> UserManager
@model ClientCommentViewModel
<div class="card px-3 align-left col-12">
        <div class="panel-item p-4 d-flex align-items-start" style="background-color:#bdbdbd;padding:2px;border-radius:4px">

            <form method="post" class="mbr-form form-with-styler" data-form-title="Mobirise Form" id="client-comment-form">
                <div class="card-text">
                    <label asp-for="Text"></label>
                    <textarea rows="5" cols="60" style="width:100%" name="Text" class="client-comment-input" id="client-comment-text" value=@Model.Text></textarea>
                    <span asp-validation-for="Text" style="color:red"></span>
                </div>
                <div class="dragArea row">
                    <div class="col-md-12  form-group">
                        <label asp-for="Author">Name</label>
                        <table style="width:100%">
                            <tr>
                                <td>
                                    <input asp-for=@Model.Author class="form-control display-7 client-comment-input" name="Author" value=@Model.Author?.ToUpper() style="padding:7px" />
                                    <input type="hidden" name="page" value=@Model.Page>
                                </td>
                                <td style="width:100px">
                                    <button type="submit"
                                            formmethod="post"
                                            asp-area=""
                                            asp-controller="Establishment"
                                            asp-action="AddComment"
                                            id="client-comment-form"
                                            class="btn btn-primary btn-form display-4"
                                            style="height:34px;
                                                width:100px;
                                                float:right">
                                        Comment
                                    </button>
                                </td>
                            </tr>
                        </table>

                    </div>
                </div>
            </form>
        </div>
</div>

RestaurantService/Views/Comment/_LeaveClientCommentPartial.cshtml
@inject UserManager<ApplicationUser> UserManager
@model ClientCommentViewModel
<div class="card px-3 align-left col-12">
    @if (!User.IsInRole("Moderator"))
    {
    <div class="panel-item p-4 d-flex align-items-start" style="background-color:#bdbdbd;padding:2px;border-radius:4px">

        <form method="post" class="mbr-form form-with-styler" data-form-title="Mobirise Form" id="client-comment-form">
            <div class="card-text">
                <label asp-for="Text"></label>
                <textarea rows="5" cols="60" style="width:100%" name="Text" class="client-comment-input" id="client-comment-text" value=@Model.Text></textarea>
                <span asp-validation-for="Text" style="color:red"></span>
            </div>
            <div class="dragArea row">
                <div class="col-md-12  form-group">
                    <label asp-for="Author">Name</label>
                    <table style="width:100%">
                        <tr>
                            <td>
                                <input asp-for=@Model.Author class="form-control display-7 client-comment-input" name="Author" value=@Model.Author?.ToUpper() style="padding:7px" />
                                <input type="hidden" name="EstablishmentId" class="client-comment-input" value=@Model.EstablishmentId id="client-comment-establishmentId">
                                @*<input type="hidden" name="IsModerated" class="client-comment-input" value=@Model.IsModerarted id="client-comment-ismoderated">*@
                            </td>
                            <td style="width:100px">
                                <button type="submit"
                                        formmethod="post"
                                        asp-area=""
                                        asp-controller="Establishment"
                                        asp-action="AddComment"
                                        id="client-comment-form"
                                        class="btn btn-primary btn-form display-4"
                                        style="height:34px;
                                                width:100px;
                                                float:right">
                                    Comment
                                </button>
                            </td>
                        </tr>
                    </table>

                </div>
            </div>
        </form>
    </div>
    }
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}