RestaurantService/Areas/Admin/Models/CreateUserViewModel.cs
using RestaurantService.Areas.Admin.Models;
using RestaurantService.Areas.Manager.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RestaurantService.Models.AccountViewModels
{
    public class CreateUserViewModel:IImigable
    {
        [Required]
        [Display(Name = "UserName")]
        public string UserName{ get; set;}

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public string Role { get; set; }

        public string Id { get; set; }

        public string CreateOrUpdate { get; set; }

        public List<string> Roles { get; set; }

        public ImageViewModel ImageModel { get; set; }

        public Dictionary<Tuple<string, int>, List<LogbookViewModelForManager>>Logbooks { get; set; }

        public List<int> LogbooksToLeave { get; set; }


        //public string UserNameMessage { get; set; }
        //public string EmailMessage { get; set; }
        //public string PasswordMessage { get; set; }
        //public string ConfirmPasswordMessage { get; set; }

    }
}

RestaurantService/Areas/Admin/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RestaurantService.Areas.Admin.Models
{
    public class UserViewModel
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Avatar { get; set; }
        public string Role { get; set; }
        public string AdminId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsLastAdmin { get; set; }
        public Dictionary<Tuple<string, int>, List<LogbookViewModelForManager>> Logbooks { get; set; }
    }
}

RestaurantService/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using RestaurantService.Areas.Admin.Models;
using RestaurantService.Data.Models;
using RestaurantService.Extensions;
using RestaurantService.Models;
using RestaurantService.Models.AccountViewModels;
using RestaurantService.Services;
using RestaurantService.Services.Contracts;

namespace RestaurantService.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        private const string defaultImage = "_default";

        private IMemoryCache _cache;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        //private readonly IEmailSender _emailSender;
        private readonly IUserService _userService;
        private readonly ILogbookService _logbookService;
        private readonly ILogger _logger;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IMapper<UserViewModel, ApplicationUser> _userMapper;
        private readonly IMapper<CreateUserViewModel, ApplicationUser> _createUserMapper;
        private readonly IMapper<LogbookViewModelForManager, Logbook> _logbookMapper;
        private readonly IServiceProvider _serviceProvider;

        public UserController(
            IMemoryCache cache,
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            //IEmailSender emailSender,
            IUserService userService,
            ILogbookService logbookService,
            ILogger<UserController> logger,
            IHostingEnvironment hostingEnvironment,
            IMapper<UserViewModel, ApplicationUser> userMapper,
            IMapper<CreateUserViewModel, ApplicationUser> createUserMapper,
            IMapper<LogbookViewModelForManager, Logbook> logbookMapper,
            IServiceProvider serviceProvider)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _userService = userService;
            _logbookService = logbookService;
            _logger = logger;
            _cache = cache;
            _hostingEnvironment = hostingEnvironment;
            _userMapper = userMapper;
            _createUserMapper = createUserMapper;
            _logbookMapper = logbookMapper;
            _serviceProvider = serviceProvider;
        }

        [TempData]
        public string ErrorMessage { get; set; }

        [Area("Admin")]
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> CreateUser(string returnUrl = null)
        {
            var model = new CreateUserViewModel()
            {
                ImageModel = new ImageViewModel()
                {
                    StyleClass= "border-radius:50%;width:300px;padding-top:10px;padding-bottom:10px;",
                    Default= "../../../images/avatars/_default.jpg"
                }
            };
            _cache.Set(_userManager.GetUserName(User), model);
            ViewData["ReturnUrl"] = returnUrl;
            var roles = await _userService.ListRoles();
            _cache.Set("Roles", roles);
            ViewBag.Roles = roles;
            var cacheModel=_cache.Get<CreateUserViewModel>(_userManager.GetUserName(User));
            return View(cacheModel);
        }

        [Area("Admin")]
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateUser(CreateUserViewModel model,string role, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            var cacheModel = _cache.Get<CreateUserViewModel>(_userManager.GetUserName(User));
            var imgModel = cacheModel.ImageModel;
            
            ApplicationUser user = null;
            if (!string.IsNullOrEmpty(model.UserName))
            {
                user = await _userService.FindUserByName(model.UserName);
                if (user != null && user.IsDeleted != true)
                {
                ModelState.AddModelError(string.Empty, "UserName already exists!");
                }
            }
            if (!string.IsNullOrEmpty(model.UserName)
                && !string.IsNullOrEmpty(model.Email)
                && !string.IsNullOrEmpty(model.Password)
                && model.Password==model.ConfirmPassword
                && (user==null|| user.IsDeleted))
            {
                IdentityResult result = null;
                var newFileName = model.UserName;

                imgModel.SaveByteImageInWwwroot(defaultImage,
                                    "images/avatars/",
                                    ref newFileName,
                                    _hostingEnvironment);
                string webRootPath = _hostingEnvironment.WebRootPath;
                if (!System.IO.File.Exists(webRootPath + "/images/avatars/" + newFileName + ".jpg")) newFileName = defaultImage;

                if (user != null && user.IsDeleted)
                {
                    user.Email = model.Email;
                    user.UserName = model.UserName;
                    user.IsDeleted = false;
                    user.PasswordHash = _userManager.PasswordHasher.HashPassword(user, model.Password);
                    user.Avatar = newFileName;
                    user.AdminId = _userManager.GetUserId(User);
                    user.Role = role;
                    result = await _userManager.UpdateAsync(user);
                }
                else
                {
                    user = new ApplicationUser {
                        UserName = model.UserName,
                        Email = model.Email,
                        Avatar = newFileName,
                        Role = role,
                        AdminId= _userManager.GetUserId(User)
                };
                    result = await _userManager.CreateAsync(user, model.Password);
                }
                if (result.Succeeded)
                {
                    _logger.LogInformation("User created a new account with password.");
                    await _userManager.AddToRoleAsync(user, role);
                    _cache.Remove(_userManager.GetUserName(User));
                    _cache.Remove("Roles");
                    return View("Details", _userMapper.Map(user));
                }
                AddErrors(result);
            }

            model.ImageModel = imgModel;
            ViewBag.Roles = _cache.Get<List<string>>("Roles");
            return View(model);
        }

        [Area("Admin")]
        [HttpGet]
        public async Task<IActionResult> UpdateUser(string id)
        {
            var user = await this._userService.FindUserById(id);
            user= await this._userService.SetRole(user);

            var model = this._createUserMapper.Map(user);
            model.CreateOrUpdate = "update";
            _cache.Set(_userManager.GetUserName(User), model);

            if (user.Role == "Manager")
            {
                model.Logbooks = await this.DivideLogbooksModelsByEstablishments(user);
            }

            return View("CreateUser", model);
        }

        [Area("Admin")]
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> UpdateUser(CreateUserViewModel model)
        {
            var cacheModel = _cache.Get<CreateUserViewModel>(_userManager.GetUserName(User));
            var imgModel = cacheModel.ImageModel;
            model.ImageModel = imgModel;
            var user = await this._userService.FindUserById(model.Id);
            user = await this._userService.SetRole(user);
            ApplicationUser foundUser = null;
            if (!string.IsNullOrEmpty(model.UserName)&&model.UserName!=user.UserName)
            {
                foundUser = await this._userService.FindUserByName(model.UserName);
            }

            if (!string.IsNullOrEmpty(model.UserName)
                && !string.IsNullOrEmpty(model.Email)
                && (foundUser == null || foundUser.IsDeleted))
            {
                IdentityResult result = null;
                var newFileName = "";
                if (string.IsNullOrEmpty(user.Avatar) || user.Avatar == defaultImage)
                    newFileName = model.UserName;
                else
                    newFileName = user.Avatar;
                    imgModel.SaveByteImageInWwwroot(newFileName,
                                        "images/avatars/",
                                        ref newFileName,
                                        _hostingEnvironment);
                string webRootPath = _hostingEnvironment.WebRootPath;
                if (!System.IO.File.Exists(webRootPath + "/images/avatars/" + newFileName + ".jpg")) newFileName = defaultImage;

                user.UserName = model.UserName;
                user.IsDeleted = false;
                user.Email = model.Email;
                //user.PasswordHash = _userManager.PasswordHasher.HashPassword(user, model.Password);
                user.Avatar = newFileName;
                user.AdminId = _userManager.GetUserId(User);
                if(user.Role=="Manager" && model?.LogbooksToLeave!=null)
                {
                    await this._userService.UnassignUserFromLogbooks(user.Id, model.LogbooksToLeave);
                }
                    result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User created a new account with password.");

RestaurantService/Controllers/InputController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using RestaurantService.Areas.Manager.Models;
using RestaurantService.Models;
using RestaurantService.Models.AccountViewModels;

namespace RestaurantService.Controllers
{
    public class InputController : Controller
    {
        private IMemoryCache _cache;
        private readonly UserManager<ApplicationUser> _userManager;

        public InputController(IMemoryCache cache, UserManager<ApplicationUser> userManager)
        {
            _cache = cache;
            _userManager = userManager;
        }

        [HttpPost("UploadImage")]
        public async Task<IActionResult> UploadImage(ImageViewModel imagemodel)
        {
            var parentmodel = _cache.Get<IImigable>(_userManager.GetUserName(User));
            imagemodel.StyleClass = parentmodel.ImageModel.StyleClass;
            if (imagemodel.FormImage != null && Path.GetExtension(imagemodel.FormImage.FileName).ToLower() == ".jpg")
            {

                using (var memoryStream = new MemoryStream())
                {
                    if (imagemodel.FormImage != null)
                    {
                        await imagemodel.FormImage.CopyToAsync(memoryStream);
                        imagemodel.ByteImage = memoryStream.ToArray();
                    }
                }
            }
            parentmodel.ImageModel = imagemodel;
            _cache.Set(_userManager.GetUserName(User), parentmodel);
            return PartialView("_UploadImagePartial", imagemodel);
        }
    }
}

RestaurantService/Areas/Admin/Views/User/CreateUser.cshtml
@model CreateUserViewModel
@{
    ViewData["Title"] = "Create user";
}

<section class="mbr-section form1 cid-rrvJasU7AL" id="form1-9">


    <div class="container">
        <div class="row justify-content-center">
            <div class="media-container-column col-lg-8" style="background-color:lightgray">
                <h2 class="mbr-section-title align-center pb-3 mbr-fonts-style display-2">
                    @if (Model.CreateOrUpdate == "update")
                    {
                        <span>UPDATE @Model.Role.ToUpper()</span>
                    }
                    else
                    {
                        <span>
                            CREATE USER
                        </span>
                    }
                </h2>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div id="partial" class="media-container-column col-lg-8" style="background-color:lightgray">
                @await Html.PartialAsync("_UploadImagePartial", Model.ImageModel)
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="media-container-column col-lg-8" data-form-type="formoid" style="background-color:lightgray">
                <form id="uploadForm" asp-area="" asp-controller="Input" asp-action="UploadImage" method="post" enctype="multipart/form-data" asp-accept="*.jpg" class="mbr-form form-with-styler" data-form-title="Mobirise Form">
                    <div class="dragArea row">
                        <div class="col-md-12">
                            <label for="NewImage">Upload Image</label>
                            <table style="width:100%">
                                <tr>
                                    <td>
                                        <input asp-for=@Model.ImageModel.FormImage class="form-control display-7" style="padding:7px" />
                                    </td>
                                    <td style="width:100px">
                                        <input type="submit"
                                               id="button" formmethod="post"
                                               class="btn btn-primary btn-form display-4"
                                               style="height:34px;
                                                width:100px;
                                                float:right"
                                               value="Upload" />
                                    </td>
                                </tr>
                            </table>

                        </div>
                    </div>
                </form>


                <form asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post" class="mbr-form form-with-styler" data-form-title="Mobirise Form">

                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="dragArea row">
                        <div class="col-md-6  form-group">
                            <label asp-for="UserName"></label>
                            <input asp-for=@Model.UserName class="form-control display-7" value=@Model.UserName />
                            <span asp-validation-for="UserName" class="text-danger"></span>
                            @*<span class="text-danger">@Model.UserNameMessage</span>*@
                        </div>
                        <div class="col-md-6  form-group">
                            <label asp-for="Email"></label>
                            <input asp-for=@Model.Email class="form-control display-7" value=@Model.Email />
                            <span asp-validation-for="Email" class="text-danger"></span>
                            @*<span class="text-danger">@Model.EmailMessage</span>*@
                        </div>
                    </div>
                    @if (Model.CreateOrUpdate != "update")
                    {
                        <div class="dragArea row">
                            <div class="col-md-6  form-group">
                                <label asp-for="Password"></label>
                                <input asp-for="Password" class="form-control" value=@Model.Password />
                                <span asp-validation-for="Password" class="text-danger"></span>
                                @*<span class="text-danger">@Model.PasswordMessage</span>*@
                            </div>
                            <div class="col-md-6  form-group">
                                <label asp-for="ConfirmPassword"></label>
                                <input asp-for="ConfirmPassword" class="form-control" value=@Model.ConfirmPassword />
                                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                                @*<span class="text-danger">@Model.ConfirmPasswordMessage</span>*@
                            </div>
                        </div>
                    }
                    @if (Model.CreateOrUpdate != "update")
                    {
                        <div class="form-group">
                            <label asp-for="Role" style="margin-right:20px"></label>
                            @foreach (var item in ViewBag.Roles)
                            {
                                <span class="radio" style="display:inline-block;margin-left:33px;">
                                    <input type="radio"
                                           name="role"
                                           value="@item"
                                           @if (item == "Manager") { <text> checked="checked" </text> } /> @item
                                    </span>
                                }
                        </div>
                    }
                    else
                    {
                        if (Model.Logbooks != null && Model.Logbooks.Count > 0)
                        {
                            <div class="col-md-12  form-group">

                                @foreach (var e in Model.Logbooks)
                                {
                                    <div>
                                        <table style="width:100%;border-bottom:1px solid white">
                                            <tr>
                                                <td>
                                                    <b><a href="/Admin/CreateEstablishment/Created/@e.Key.Item2" style="font-size:1.2rem;font-weight:500"> @e.Key.Item1:</a></b>
                                                </td>
                                                <td style="text-align:right">
                                                    @foreach (var l in e.Value)
                                                    {
                                                        <input type="checkbox" value=@l.Id name="LogbooksToLeave" checked="checked" style="vertical-align:text-bottom" class="existing-logbooks" />
                                                        <span><a href="/Admin/Logbook/UpdateLogbook/@l.Id">@l.Name </a> </span>
                                                    }
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                }
                            </div>
                        }

                    }

                    <div class="col-md-12 input-group-btn align-center" style="padding-bottom:20px">
                        @if (Model.CreateOrUpdate == "update")
                        {
                            <button type="submit" class="btn btn-primary btn-form display-4" asp-area="Admin" asp-controller="User" asp-action="UpdateUser" asp-route-name="@Model.UserName" formmethod="post">Update</button>
                        }
                        else
                        {
                            <button type="submit" class="btn btn-primary btn-form display-4" asp-area="Admin" asp-controller="User" asp-action="CreateUser" asp-route-name="@Model.UserName" formmethod="post">Create</button>
                        }
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

RestaurantService/Areas/Admin/Views/User/Details.cshtml
@model UserViewModel
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Details";
}
<section class="mbr-section form1 cid-rrvJasU7AL" id="form1-9">


    <div class="container">
        <div class="row justify-content-center">
            <div style="text-align:center;font-style:normal">
                <br />
                <h2>@Model.UserName</h2>
                <div>
                    <img src=@Model.Avatar width="200" />
                </div>
                <div style="font-size:1.2rem;font-weight:500">
                    @Model.Role
                </div>
                <br />
                <div style="align-items:center;width:100%">
                    <div style="text-align:left">
                        @if (Model.Logbooks != null && Model.Logbooks.Count > 0)
                        {

                            @foreach (var e in Model.Logbooks)
                            {
                                <table style="width:100%;border-bottom:1px solid white">
                                    <tr>
                                        <td >
                                            <b><a href="/Admin/CreateEstablishment/Created/@e.Key.Item2" style="font-size:1.2rem;font-weight:500"> @e.Key.Item1:</a></b>
                                        </td>
                                        <td style="text-align:right;">
                                            @foreach (var l in e.Value)
                                            {
                                                <span><a href="/Admin/Logbook/UpdateLogbook/@l.Id">[@l.Name]</a></span>
                                            }
                                        </td>
                                    </tr>
                                </table>
                            }
                        }
                    </div>
                </div>
                <br />
                <p>
                    @if (Model.AdminId == UserManager.GetUserId(User))
                    {
                        <a class="btn btn-primary" role="button" style="font-size:14px" asp-area="Admin" asp-controller="User" asp-action="UpdateUser" asp-route-id="@Model.Id">Update User</a>
                    }
                </p>
            </div>

        </div>
    </div>
</section>